### ISSUE TITLE
Aktivität anzeigen

### ISSUE THREAD

**Issue by xXxH4n5Wur5t360NoPullsxXx** [sweIhm/sweiproject-tg1a-1#11]
Ich, als Student, möchte die Aktivitäten, die eingestellt worden sind, sehen.

**Comment by xXxH4n5Wur5t360NoPullsxXx** [comment]
Aktzeptanz-Kriterien
* Alle Aktivitäten, die in der Datenbank sind, müssen auf einer Seite angezeigt werden

**Comment by xXxH4n5Wur5t360NoPullsxXx** [comment]
Geht, ist okay

**Comment by hmkrivoj** [comment]
Dann schließe ich das Issue.
