### ISSUE TITLE
 Frontend scheint keine requests zu senden

### ISSUE THREAD

**Issue by xXxH4n5Wur5t360NoPullsxXx** [sweIhm/sweiproject-tg1a-1#14]
Dimi, dein Frontend sendet keine Requests. Hast du die Links hardgecodet bzw. keine relativen links?

**Comment by hmkrivoj** [comment]
Bitte testen, ob Bugfix funktioniert

**Comment by xXxH4n5Wur5t360NoPullsxXx** [comment]
Scheint zu funktionieren. Closeriere dann mal die Angelegenheit
