### ISSUE TITLE
Redirect von Activation-Controller auf index

### ISSUE THREAD

**Issue by hmkrivoj** [sweIhm/sweiproject-tg1a-1#15]
Ein redirect wäre imo besser, da es nicht sehr benutzerfreundlich ist, wenn man beim klicken des Aktivierungslinks auf einer json-Page landet.

**Comment by xXxH4n5Wur5t360NoPullsxXx** [comment]
Verschieben wir mal auf den nächsten Sprint. Wollen die Kerle mal nicht überfordern

**Comment by hmkrivoj** [comment]
Es ist Mittwoch meine Kerle 🐸

**Comment by hmkrivoj** [comment]
Routing Module von Angular ist für dieses Thema hilfreich

**Comment by hmkrivoj** [comment]
Das Spring-Mapping auf /error sollte auch auf index.html zeigen
Vorschlag: von /error ein redirect zu /dashboard;alert=pagenotfound (Siehe dazu ActivationController und HomeController) und den Parameter dann dementsprechend im Dashboard auf Frontend-Seite handeln

**Comment by xXxH4n5Wur5t360NoPullsxXx** [comment]
/error mapping ist bisschen aufwendiger. Benötigt auch einiges an Refactoring, damit es stimmig ist.

**Comment by hmkrivoj** [comment]
Dann belassen wir es dabei
