### ISSUE TITLE
Benachrichtigung

### ISSUE THREAD

**Issue by xXxH4n5Wur5t360NoPullsxXx** [sweIhm/sweiproject-tg1a-1#16]
Guten Tag, wenn ich eine Aktivität erstellt habe, oder einen Kommentar hinterlassen habe, möchte ich über weitere Beiträge benachrichtigt werden.

**Comment by xXxH4n5Wur5t360NoPullsxXx** [comment]
Aktzeptanz-Kriterien
- Wenn ein Kommentar pfostiert wird, wird an alle Teilnehmenden in der Aktivität eine E-Mail versendet, die auf die Aktivität verweist, und den pfostierten Kommentar beinhaltet
- Tests, sofern möglich

**Comment by hmkrivoj** [comment]
Es fehlt noch die Benachrichtigung der Kommentatoren

**Comment by hmkrivoj** [comment]
Kommentatoren werden nun benachrichtigt
Email controller ist hinreichend mit tests abgedeckt

**Comment by xXxH4n5Wur5t360NoPullsxXx** [comment]
Sieht ganz gescheit aus
