### ISSUE TITLE
Aktivität erstellen

### ISSUE THREAD

**Issue by xXxH4n5Wur5t360NoPullsxXx** [sweIhm/sweiproject-tg1a-1#4]
Als Lehrender möchte ich meine Angebote für Bachelor Arbeiten online stellen, damit Studierende sie sich anschauen können.

**Comment by xXxH4n5Wur5t360NoPullsxXx** [comment]
Aktzeptanz-Kriterien
- Ein Pfosten soll eingereicht werden können
- Pfosten persistent in Datenbank
- Verifikation beim erstellen des Pfosten durch E-Mail

**Comment by xXxH4n5Wur5t360NoPullsxXx** [comment]
Geht. Passt.

**Comment by hmkrivoj** [comment]
Dann schließe ich das Issue hiermit.
