### ISSUE TITLE
Aktivität kommentieren

### ISSUE THREAD

**Issue by xXxH4n5Wur5t360NoPullsxXx** [sweIhm/sweiproject-tg1a-1#9]
Ich, Karsten, möchte zu Angeboten fragen stellen können.

**Comment by xXxH4n5Wur5t360NoPullsxXx** [comment]
Aktzeptanz-Kriterien
- Zu einer spezifischen Aktivität kann man Fragen einreichen, die beim Autor des Angebots auch eingehen.

**Comment by hmkrivoj** [comment]
Das kommentieren scheint soweit zu funktionieren... Review erwünscht

**Comment by xXxH4n5Wur5t360NoPullsxXx** [comment]
Sieht ganz gescheit aus
